ServerName localhost
<VirtualHost *:80>
    DocumentRoot /var/www/html/public
    DirectoryIndex index.php

    <Directory /var/www/html/public>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    <FilesMatch "^(?!index\.php$).*\.php$">
        Require all denied
    </FilesMatch>
    <FilesMatch "^\.">
        Require all denied
    </FilesMatch>
    <Directory /var/www/html/public/media>
        <FilesMatch "(?i)\.(php|phtml|phar|html?)$">
            Require all denied
        </FilesMatch>
    </Directory>
    Header always set X-Robots-Tag "noindex, nofollow, noarchive"
    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
